name: Build and Sign Firefox Extension

on:
  push:
    branches:
      - main  # oder den Branch deiner Wahl

jobs:
  build-sign-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Aktualisiert auf die neueste Version

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Setzt Node.js auf eine unterstützte Version

    # Packen der Erweiterung
    - uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: './'
        zipFilePath: 'build/ITSecScore.zip'

    # Signieren der Erweiterung
    - uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@v1
      with:
        zipFilePath: 'build/ITSecScore.zip'
        xpiFilePath: 'build/ITSecScore.signed.xpi'
        timeoutMs: 200000
        jwtIssuer: ${{ secrets.MOZILLA_ISSUER }}
        jwtSecret: ${{ secrets.MOZILLA_SECRET }}

    # Hochladen der .xpi-Datei als Artifact
    - uses: actions/upload-artifact@v3  # Aktualisiert auf die neueste Version
      with:
        name: signed-extension
        path: build/ITSecScore.signed.xpi
