name: Build and Sign Firefox Extension

on:
  push:
    branches:
      - main  # oder den Branch deiner Wahl

jobs:
  build-sign-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Packen der Erweiterung
    - uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: './'
        zipFilePath: 'build/extension.zip'

    # Signieren der Erweiterung
    - uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@v1
      with:
        zipFilePath: 'build/extension.zip'
        xpiFilePath: 'build/extension.signed.xpi'
        jwtIssuer: ${{ secrets.MOZILLA_ISSUER }}
        jwtSecret: ${{ secrets.MOZILLA_SECRET }}

