name: Build and Sign Firefox Extension

on:
  push:
    branches:
      - main

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Pack Extension
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: './'
        zipFilePath: 'build/extension.zip'

    - name: Sign Extension
      uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@v1
      with:
        zipFilePath: 'build/extension.zip'
        xpiFilePath: 'build/extension.signed.xpi'
        jwtIssuer: ${{ secrets.MOZILLA_ISSUER }}
        jwtSecret: ${{ secrets.MOZILLA_SECRET }}

    - name: Upload Signed Extension as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: signed-extension
        path: 'build/extension.signed.xpi'
