name: Build and Sign Firefox Extension

on:
  push:
    branches:
      - main  # oder den Branch deiner Wahl

jobs:
  build-sign-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Aktualisiert auf die neueste Version

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Setzt Node.js auf eine unterstützte Version

    # Packen der Erweiterung
    - uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: './'
        zipFilePath: 'build/ITSecScore.zip'

    # Signieren der Erweiterung
    - uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@v1
      with:
        zipFilePath: 'build/ITSecScore.zip'
        xpiFilePath: 'build/ITSecScore.signed.xpi'
        timeoutMs: 500000
        jwtIssuer: ${{ secrets.MOZILLA_ISSUER }}
        jwtSecret: ${{ secrets.MOZILLA_SECRET }}

    # ls von dem Ordner, in dem die .xpi-Datei erstellt wurde
    - name: List build directory
      run: ls build

    # Create a release
    - uses: meeDamian/github-release@v1.0.0
      with:
        files: build/ITSecScore.signed.xpi
        tag: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}