name: Build Unsigned Extension Artifact

on: push

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Update version in manifest.json to commit SHA
      run: |
        VERSION=${GITHUB_SHA::8}
        jq --arg ver "$VERSION" '.version=$ver' src/manifest.json > src/temp.json && mv src/temp.json src/manifest.json
      shell: bash

    - name: Pack Extension Directory
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: './src'
        zipFilePath: 'build/ITSecScore-unsigned.zip'

    - name: Upload Unsigned Extension as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: unsigned-extension
        path: build/ITSecScore-unsigned.zip
